### ISSUE TITLE
外部ファイル読み込み後、検索を行うと落ちる

### ISSUE THREAD

**Issue by Fafsfalira** [yuugokku/FistirDictionary#2]
・やったこと
辞書ファイルとして外部ファイルを読み込んだ。検索を実行するとプログラムが落ちた。
辞書グループの指定はユーゴック語になっている。

・想定される動作
検索が実行され、結果が表示される。

**Comment by yuugokku** [comment]
`fdic-setting.json` ファイルを見せてください。

**Comment by Fafsfalira** [comment]
{
  "Username": null,
  "Email": null,
  "DictionaryGroups": [
    {
      "GroupName": "ユーゴック語",
      "Dictionaries": [
        "C:\\Users\\sashi\\Documents\\FistirDictionary_v0.1.0\\FistirDictionary_0.1.0\\yuugokku_sukarmakku.fdic"
      ],
      "DefaultDictionaryIndex": null
    },
    {
      "GroupName": "リパライン語",
      "Dictionaries": [
        "C:\\Users\\sashi\\Documents\\FistirDictionary_v0.1.0\\FistirDictionary_0.1.0\\lineparine_japeovirle.fdic"
      ],
      "DefaultDictionaryIndex": null
    }
  ],
  "DefaultGroupIndex": null
}

**Comment by yuugokku** [comment]
Fafs falira sashimi氏に渡したユーゴック語辞書ファイルに含まれる韻律スクリプトのパスが私の環境におけるものだったため、ファイル読み込みエラーが発生していたようです。
以下の方向で改修します。

- 韻律スクリプトのパスは `fdic-setting.json` 内で設定する。
    - スクリプトは辞書と分離して管理させたいので、環境ごとに設定ファイルで指定するのが理にかなっている。
- 韻律スクリプトのパスは辞書ファイルごとに個別に設定できる。
    - 辞書グループ機能は、語派や語族ごとにまとめて利用する形態が考えられるが、一般に韻律は言語によって異なるため、グループごとでなく辞書ファイルごとに設定するのが望ましいから。
